name: Python app with Github Actions

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run:
          make install
      - name: Post Install
        run:
          make post-install    
      - name: Format with black
        run:
          make format
      - name: Lint with pylint
        run:
          make lint
      - name: Test with pytest
        run:
          make test

#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: configure
#       run: ./configure

#     - name: Install dependencies
#       run: make

#     - name: Run check
#       run: make check

#     - name: Run distcheck
#       run: make distcheck
